version: '3'
volumes:
  database_data:
    driver: local

services:
  postgres:
    image: postgres:11.0-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    container_name: pg-test
    ports:
      - "5432:5432"
    volumes:
      - ./database_data:/var/lib/postgresql/data

